package com.example.sparcs_new.ui.theme.theme

import androidx.compose.ui.graphics.Color


val theme_light_primary = Color(0xFF375298)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFFCEE5FF)
val theme_light_onPrimaryContainer = Color(0xFF0F4A73)
val theme_light_secondary = Color(0xFF51606F)
val theme_light_onSecondary = Color(0xFFF1F2F6)
val theme_light_secondaryContainer = Color(0xFFD5E4F7)
val theme_light_onSecondaryContainer = Color(0xFF3A4857)
val theme_light_tertiary = Color(0xFF68587A)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFD8D4EE)
val theme_light_onTertiaryContainer = Color(0xFF504061)
val theme_light_error = Color(0xFFBA1A1A)
val theme_light_errorContainer = Color(0xFFFFFFFF)
val theme_light_onError = Color(0xFFFFDAD6)
val theme_light_onErrorContainer = Color(0xFF93000A)
val theme_light_background = Color(0xFFF0F2F5)
val theme_light_onBackground = Color(0xFF201A1B)
val theme_light_surface = Color(0xFF2D3135)
val theme_light_onSurface = Color(0xFFEFF1F6)
val theme_light_surfaceVariant = Color(0xFFFFFFFF)
val theme_light_onSurfaceVariant = Color(0xFF42474E)
val theme_light_outline = Color(0xFF72777F)
val theme_light_inverseOnSurface = Color(0xFFEFF1F6)
val theme_light_inverseSurface = Color(0xFF2D3135)
val theme_light_inversePrimary = Color(0xFF9BCBFB)
val theme_light_surfaceTint = Color(0xFF406098)
val theme_light_outlineVariant = Color(0xFFC2C7CF)
val theme_light_scrim = Color(0xFF101010)

val theme_dark_primary = Color(0xFF9BCBFB)
val theme_dark_onPrimary = Color(0xFF003353)
val theme_dark_primaryContainer = Color(0xFF0F4A73)
val theme_dark_onPrimaryContainer = Color(0xFFCEE5FF)
val theme_dark_secondary = Color(0xFFB9C8DA)
val theme_dark_onSecondary = Color(0xFF243240)
val theme_dark_secondaryContainer = Color(0xFF3A4857)
val theme_dark_onSecondaryContainer = Color(0xFFD5E4F7)
val theme_dark_tertiary = Color(0xFFD3BFE6)
val theme_dark_onTertiary = Color(0xFF392A49)
val theme_dark_tertiaryContainer = Color(0xFF504061)
val theme_dark_onTertiaryContainer = Color(0xFFEFDBFF)
val theme_dark_error = Color(0xFFFFB4AB)
val theme_dark_errorContainer = Color(0xFF690005)
val theme_dark_onError = Color(0xFF93000A)
val theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val theme_dark_background = Color(0xFF201A1B)
val theme_dark_onBackground = Color(0xFFE0E2EB)
val theme_dark_surface = Color(0xFF101418)
val theme_dark_onSurface = Color(0xFFE0E2E8)
val theme_dark_surfaceVariant = Color(0xFF36393E)
val theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val theme_dark_outline = Color(0xFF8C9198)
val theme_dark_inverseOnSurface = Color(0xFF2D3135)
val theme_dark_inverseSurface = Color(0xFFE0E2E8)
val theme_dark_inversePrimary = Color(0xFF2F628C)
val theme_dark_surfaceTint = Color(0xFFB0CAFF)
val theme_dark_outlineVariant = Color(0xFF42474E)
val theme_dark_scrim = Color(0xFFEEEEEE)
